version: "3"
services:
  # start the ganache cli container
  ganache-cli:
    container_name: ganache-cli
    build:
      context: ./docker/ganache-cli
    ports:
      - 5545:8545
  truffle_suite:
    container_name: truffle_suite
    build:
      context: ./docker/truffle-suite # volumes
    volumes:
      - ".:/workspace"
    stdin_open: true # docker run -i
    tty: true # docker run -t
  dapp:
    restart: always
    container_name: dapp
    build:
      context: ./dapp
    ports:
      - 3000:3000
    command: yarn dev
    volumes:
      - ./dapp/:/usr/src/dapp/
      - nodemodules-dapp:/usr/src/dapp/node_modules

volumes:
  nodemodules-dapp: {}
